"""
Generates a one-page 'Risk Card' PDF from a ClassificationResult.
"""

from datetime import date
from functools import partial
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from classifier import ClassificationResult

NAVY = colors.HexColor("#1B2733")
SLATE = colors.HexColor("#5A6B7A")
LIGHT_RULE = colors.HexColor("#E2E6EA")
PAGE_W, PAGE_H = letter
HEADER_HEIGHT = 1.15 * inch

TIER_COLORS = {
    "prohibited": colors.HexColor("#7A1F2B"),
    "high-risk": colors.HexColor("#C0392B"),
    "limited-risk": colors.HexColor("#C77D14"),
    "minimal-risk": colors.HexColor("#1E8449"),
}

TIER_LABELS = {
    "prohibited": "PROHIBITED \u2014 Unacceptable Risk",
    "high-risk": "HIGH-RISK",
    "limited-risk": "LIMITED-RISK",
    "minimal-risk": "MINIMAL-RISK",
}

DISCLAIMER = (
    "This is an automated first-pass triage only and does not constitute "
    "legal advice. It is generated by an LLM against a condensed summary of "
    "Regulation (EU) 2024/1689 and may be incomplete, out of date, or "
    "wrong for ambiguous or novel use cases. Confirm any consequential "
    "classification with qualified legal counsel."
)


def _draw_header_and_footer(canvas, doc, result):
    canvas.saveState()

    # Full-bleed navy header band
    canvas.setFillColor(NAVY)
    canvas.rect(0, PAGE_H - HEADER_HEIGHT, PAGE_W, HEADER_HEIGHT, stroke=0, fill=1)

    # Title
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 19)
    canvas.drawString(0.6 * inch, PAGE_H - 0.55 * inch, "AI System Risk Card")

    # Subtitle
    canvas.setFont("Helvetica", 9.5)
    canvas.setFillColor(colors.HexColor("#B8C4CE"))
    canvas.drawString(
        0.6 * inch, PAGE_H - 0.78 * inch, "EU AI Act \u2014 First-Pass Compliance Triage"
    )

    # Date, right-aligned
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(
        PAGE_W - 0.6 * inch, PAGE_H - 0.55 * inch, f"Generated {date.today().isoformat()}"
    )

    # Thin accent line under header, colored by tier
    tier_color = TIER_COLORS.get(result.tier, colors.grey)
    canvas.setFillColor(tier_color)
    canvas.rect(0, PAGE_H - HEADER_HEIGHT - 0.06 * inch, PAGE_W, 0.06 * inch, stroke=0, fill=1)

    # Footer
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(SLATE)
    canvas.drawString(
        0.6 * inch, 0.4 * inch, "AI System Risk & Compliance Classifier \u2014 portfolio project"
    )
    canvas.drawRightString(PAGE_W - 0.6 * inch, 0.4 * inch, "Page 1 of 1")

    canvas.restoreState()


def _build_styles():
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="TierBadge",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=colors.white,
            leading=17,
        )
    )
    styles.add(
        ParagraphStyle(
            name="MetaLabel",
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=SLATE,
            leading=11,
        )
    )
    styles.add(
        ParagraphStyle(
            name="MetaValue",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=colors.HexColor("#222222"),
            leading=13,
        )
    )
    styles.add(
        ParagraphStyle(
            name="SectionHeading",
            fontName="Helvetica-Bold",
            fontSize=10.5,
            spaceBefore=12,
            spaceAfter=5,
            textColor=NAVY,
        )
    )
    styles.add(
        ParagraphStyle(
            name="Body",
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor("#2A2A2A"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="Disclaimer",
            fontName="Helvetica-Oblique",
            fontSize=7.5,
            leading=10,
            textColor=SLATE,
        )
    )
    return styles


def generate_risk_card(result: ClassificationResult) -> bytes:
    """Returns the PDF file content as bytes, ready to write or stream."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=HEADER_HEIGHT + 0.35 * inch,
        bottomMargin=0.65 * inch,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
    )
    styles = _build_styles()
    story = []

    tier_color = TIER_COLORS.get(result.tier, colors.grey)
    tier_label = TIER_LABELS.get(result.tier, result.tier.upper())

    # Tier badge, left cell colored; right cell holds confidence/borderline meta
    borderline_text = (
        "\u26a0 Borderline \u2014 recommend human review" if result.borderline else "\u2014"
    )
    badge_table = Table(
        [
            [
                Paragraph(tier_label, styles["TierBadge"]),
                Paragraph("CONFIDENCE", styles["MetaLabel"]),
                Paragraph("REVIEW FLAG", styles["MetaLabel"]),
            ],
            [
                "",
                Paragraph(result.confidence.capitalize(), styles["MetaValue"]),
                Paragraph(borderline_text, styles["MetaValue"]),
            ],
        ],
        colWidths=[3.6 * inch, 1.6 * inch, 1.6 * inch],
        rowHeights=[24, 18],
    )
    badge_table.setStyle(
        TableStyle(
            [
                ("SPAN", (0, 0), (0, 1)),
                ("BACKGROUND", (0, 0), (0, 1), tier_color),
                ("BACKGROUND", (1, 0), (-1, 1), colors.HexColor("#F4F6F7")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (0, -1), 12),
                ("LEFTPADDING", (1, 0), (-1, -1), 12),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (1, 0), (1, 0), 0.5, LIGHT_RULE),
                ("LINEBELOW", (2, 0), (2, 0), 0.5, LIGHT_RULE),
            ]
        )
    )
    story.append(badge_table)
    story.append(Spacer(1, 6))

    def section(title, body_flowables):
        story.append(Paragraph(title.upper(), styles["SectionHeading"]))
        story.append(HRFlowable(width="100%", thickness=0.6, color=LIGHT_RULE, spaceAfter=6))
        story.extend(body_flowables)

    section("System Description", [Paragraph(result.system_description, styles["Body"])])
    section("Applicable Article / Annex", [Paragraph(result.primary_article_or_annex, styles["Body"])])
    section("Reasoning", [Paragraph(result.reasoning, styles["Body"])])

    if result.borderline and result.borderline_note:
        section("Borderline Note", [Paragraph(result.borderline_note, styles["Body"])])

    checklist_items = [
        ListItem(Paragraph(item, styles["Body"]), leftIndent=10, spaceAfter=2)
        for item in result.documentation_checklist
    ]
    section(
        "Documentation Checklist",
        [ListFlowable(checklist_items, bulletType="bullet", start="\u2022")],
    )

    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", thickness=0.6, color=LIGHT_RULE, spaceAfter=6))
    story.append(Paragraph(DISCLAIMER, styles["Disclaimer"]))

    doc.build(
        story,
        onFirstPage=partial(_draw_header_and_footer, result=result),
        onLaterPages=partial(_draw_header_and_footer, result=result),
    )
    return buffer.getvalue()


def save_risk_card(result: ClassificationResult, path: str) -> None:
    pdf_bytes = generate_risk_card(result)
    with open(path, "wb") as f:
        f.write(pdf_bytes)


if __name__ == "__main__":
    # Manual test with a fake result (no API call needed)
    fake_result = ClassificationResult(
        tier="high-risk",
        confidence="high",
        primary_article_or_annex="Annex III(4) - Employment, recruitment and selection",
        reasoning=(
            "CV screening and candidate ranking falls under Annex III point 4 "
            "(employment/recruitment), which covers AI used to screen or filter "
            "job applications and evaluate candidates."
        ),
        documentation_checklist=[
            "Risk management system (Article 9)",
            "Technical documentation (Article 11, Annex IV)",
            "Record-keeping / logging (Article 12)",
            "Transparency to candidates (Article 13)",
            "Human oversight measures (Article 14)",
            "Conformity assessment and CE marking",
            "Registration in the EU high-risk AI database",
        ],
        borderline=False,
        borderline_note="",
        system_description="An AI tool that scans job applicants' CVs and ranks them for recruiters.",
    )
    save_risk_card(fake_result, "test_risk_card.pdf")
    print("Saved test_risk_card.pdf")
